# FreeIPA
ldap_server_fqdn: "freeipa.cluster.hcemm.eu"
ldap_vm_ip: "10.0.150.203"
ldap_domain: "cluster.hcemm.eu"
ldap_realm: "CLUSTER.HCEMM.EU"
ldap_admin_user: "admin"
ldap_admin_password_raw: "hcemm2018"
ldap_port: 389
ldap_user_base_dn: cn=users,cn=accounts,dc=cluster,dc=hcemm,dc=eu
ldap_username_attribute: uid
ldap_search_bind_dn: "uid=admin,{{ ldap_user_base_dn }}"

# user group IDs: 200000 - 299999
ldap_groups:
  - { name: wheel,            gid: "10"}
  - { name: libvirt,          gid: "201"}
  - { name: grp_hcemm,        gid: "200000"}
  - { name: grp_grost,        gid: "200001"}
  - { name: grp_klamsa,       gid: "200002"}
  - { name: grp_tpankotai,    gid: "200003"}
  - { name: grp_lpongor,      gid: "200004"}
  - { name: grp_sjuhasz,      gid: "200005"}
  - { name: grp_mroland,      gid: "200006"}
  - { name: grp_zbiacsi,      gid: "200007"}
  - { name: grp_jsequeira,    gid: "200008"}
  - { name: grp_mmanczinger,  gid: "200009"}
  - { name: grp_kvince,       gid: "200010"}
  - { name: grp_kpircs,       gid: "200011"}
  - { name: grp_nhamdani,     gid: "200012"}
  - { name: grp_bpapp,        gid: "200013"}

# user IDs: 100000 - 199999
ldap_users:
  - { email: fanni.nedenyi@hcemm.eu,        username: fnedenyi,       first: Fanni,              last: Nedenyi,        uid: "100000", groups: [grp_grost],                                  password: "fnedenyi123puli" }
  - { email: adam.tiszlavicz@hcemm.eu,      username: atiszla,        first: Adam,               last: Tiszlavicz,     uid: "100001", groups: [grp_klamsa],                                 password: "atiszla123puli" }
  - { email: alessandra.vittorini@hcemm.eu, username: avo,            first: Alessandra,         last: Vittorini,      uid: "100002", groups: [grp_grost],                                  password: "avo123puli" }
  - { email: zoltan.pahi@hcemm.eu,          username: pahizol,        first: Zoltan,             last: Pahi,           uid: "100003", groups: [grp_tpankotai],                              password: "pahizol123puli" }
  - { email: lorinc.pongor@hcemm.eu,        username: pongorls,       first: Lorinc,             last: Pongor,         uid: "100004", groups: [grp_lpongor],                                password: "pongorls123puli" }
  - { email: kolos.nemes@hcemm.eu,          username: knemes,         first: Kolos,              last: Nemes,          uid: "100005", groups: [grp_lpongor],                                password: "knemes123puli" }
  - { email: alexandra.beno@hcemm.eu,       username: abeno,          first: Alexandra,          last: Beno,           uid: "100006", groups: [grp_lpongor],                                password: "abeno123puli" }
  - { email: suliakos@yahoo.com,            username: asuli,          first: Akos,               last: Suli,           uid: "100007", groups: [grp_grost],                                  password: "asuli123puli" }
  - { email: zoltan.biacsi@inclouded.hu,    username: zbiacsi,        first: Zoltan,             last: Biacsi,         uid: "100008", groups: [grp_zbiacsi, libvirt],                       password: "zbiacsi123puli" }
  - { email: balogh.gergo@brc.hu,           username: gmbalogh,       first: Gergo Mihaly,       last: Balogh,         uid: "100009", groups: [grp_mmanczinger],                            password: "gmbalogh123puli" }
  - { email: bence.bognar@hcemm.eu,         username: bognarb,        first: Bence,              last: Bognar,         uid: "100010", groups: [grp_sjuhasz],                                password: "bognarb123puli" }
  - { email: aron.somogyi2001@gmail.com,    username: somar,          first: Aron,               last: Somogyi,        uid: "100011", groups: [grp_sjuhasz],                                password: "somar123puli" }
  - { email: anna.ascsillan@gmail.com,      username: annaascsillan,  first: Anna,               last: Ascsillan,      uid: "100012", groups: [grp_kvince],                                 password: "aascsillan123puli" }
  - { email: Joao.Sequeira@hcemm.eu,        username: jsequeira,      first: Joao,               last: Sequeira,       uid: "100013", groups: [grp_jsequeira, grp_hcemm, wheel, libvirt],   password: "jsequeira123puli" }
  - { email: Maria.Kavoosi@hcemm.eu,        username: mkavoosi,       first: Maria,              last: Kavoosi,        uid: "100014", groups: [grp_jsequeira, wheel, libvirt],              password: "mkavoosi123puli" }
  - { email: Istvan.Szepesi-Nagy@hcemm.eu,  username: sznistvan,      first: Istvan,             last: Szepesi-Nagy,   uid: "100015", groups: [grp_jsequeira],                              password: "sznistvan123puli" }
  - { email: christoph.sensen@hcemm.eu,     username: csensen,        first: Christoph,          last: Sensen,         uid: "100016", groups: [grp_hcemm],                                  password: "csensen123puli" }
  - { email: andras.vagner@hcemm.eu,        username: vandras,        first: Andras,             last: Vagner,         uid: "100017", groups: [grp_lpongor],                                password: "vandras123puli" }
  - { email: fuiszsoma@gmail.com,           username: sfuisz,         first: Szoma,              last: Fuisz,          uid: "100018", groups: [grp_kvince],                                 password: "reen3Oota6" }
  - { email: kltzsofia@gmail.com,           username: zkoltai,        first: Zsofia,             last: Klotai,         uid: "100019", groups: [grp_kpircs],                                 password: "ieCuyo0ahg" }
  - { email: zsoldos.roland@semmelweis.hu,  username: rzsoldos,       first: Roland,             last: Zsoldos,        uid: "100020", groups: [grp_kpircs],                                 password: "niMieg7iet" }
  - { email: Mustafa.kacmaz@rub.de,         username: mkacmaz,        first: Mustafa,            last: Kacmaz,         uid: "100021", groups: [grp_nhamdani],                               password: "quie0Johko" }
  - { email: thenmozhi.jr@hcemm.eu,         username: tjravi,         first: Thenmozhi Jayanthi, last: Ravi,           uid: "100022", groups: [grp_sjuhasz],                                password: "waway1Vah8" }
  - { email: huszarreka@gmail.com,          username: rhuszar,        first: Reka,               last: Huszar,         uid: "100023", groups: [grp_bpapp],                                  password: "ta0AiQuu7X" }
  - { email: tothalexandra98@gmail.com,     username: avtoth,         first: Alexandra Vivien,   last: Toth,           uid: "100024", groups: [grp_bpapp],                                  password: "piaz7voa0P" }
  - { email: szollarzorka@gmail.com,        username: zszollar,       first: Zorka,              last: Szollar,        uid: "100025", groups: [grp_tpankotai],                              password: "ekaip5queS" }
