---
- name: Wait for SSH to be available on all VMs
  ansible.builtin.wait_for:
    host: "{{ item.value.ip }}"
    port: 22
    timeout: 180
    state: started
  delegate_to: localhost
  loop: "{{ post_vms_vm_list | dict2items }}"
  run_once: false

- name: Ensure SSH key exists in ansible user known_hosts
  ansible.builtin.command: >
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts {{ item.key }} exit
  delegate_to: localhost
  loop: "{{ post_vms_vm_list | dict2items }}"
  changed_when: false

- name: Ensure SSH key exists in root user known_hosts
  ansible.builtin.command: >
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/root/.ssh/known_hosts {{ item.key }} exit
  delegate_to: localhost
  loop: "{{ post_vms_vm_list | dict2items }}"
  changed_when: false

- name: Set DNS servers and disable auto-DNS
  community.general.nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet
    state: present
    dns4:
      - 8.8.8.8
      - 1.1.1.1
    dns4_ignore_auto: true

- name: Bring connection up again
  community.general.nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    state: up
