galaxy_root: /srv/galaxy
galaxy_commit_id: release_23.0
galaxy_config_style: yaml
galaxy_layout: root-dir

galaxy_user: galaxy
galaxy_group: galaxy
galaxy_privsep_user: gxpriv
galaxy_separate_privileges: true

galaxy_db_name: galaxy
galaxy_db_user: galaxy

galaxy_bind_host: 0.0.0.0
galaxy_bind_port: 8080
