tl_accept_eula: "yes"
tl_version: "4.20.0"
tl_server_bundle: "/tmp/tl-{{ tl_version }}-server.zip"
tl_build: "4116"
tl_autoinstall_dependencies: "yes"
tl_email: joao.sequeira@hcemm.eu
tl_printers: "no"
tl_webaccess_port: 443
tl_webaccess_login_page: "/"    # default value, redirects to the current server
tl_webadm_port: 1010
tl_webadm_password: "$6$ef8b0b02b79db5e6$9d6QTuXeVYXFAQmM37UXvHAVUOtMbQBtiUUzq.9qVeY66h.1uyiSxoYNmHm2fOzOV20RIfXaTQm9SGqyx9rJg1"
tl_hostname_choice: "hostname"
tl_agent_hostname: login.cluster.hcemm.eu
