nginx_gateway_services:

  - name: "galaxy"
    server_name: "galaxy.{{ nginx_gateway_domain }}"
    backends:
      - "10.0.150.209:8080"
    tusd: "10.0.150.209:1080"
    static: true
    x_accel_redirect: true

  - name: "emma"
    server_name: "emma.{{ nginx_gateway_domain }}"
    backends:
      - "10.0.150.210:8000"

  # DoctorLLM / Open WebUI
  - name: "doctorllm"
    server_name: "doctorllm.{{ nginx_gateway_domain }}"

    backends:
      - "{{ hostvars[groups['doctorllm_server'][0]].ansible_host }}:{{ doctorllm_openwebui_port }}"

    keepalive: 64
    websocket: true

    client_max_body_size: "100M"

    proxy_connect_timeout: "60s"
    proxy_send_timeout: "3600s"
    proxy_read_timeout: "3600s"

    proxy_buffering: "off"