setup_modules_spack_version: "0.23.1"
setup_modules_spack_gcc: "14.2.0"
setup_modules_spack_packages:
  - bwa
  - sratoolkit
  - picard
  - samtools
  - py-macs3
  - bedtools2
  - py-pandas
  - miniconda3
  - apptainer
  - py-multiqc
  - seqkit
  - cdhit
