# These six tasks check the age of the existing image and rebuild it if it's older than set time
- name: Get current time
  ansible.builtin.command: date +%s
  register: now_ts
  changed_when: false

- name: Get image modification time
  ansible.builtin.shell: >
    set -o pipefail
    date -d "$(wwctl image list --long | grep almalinux-9 | awk '{print $(NF-5)" "$(NF-4)" "$(NF-3)')" +%s
  register: image_mod_ts
  changed_when: false

- name: Calculate image age in minutes
  ansible.builtin.set_fact:
    image_age_minutes: "{{ (now_ts.stdout | int - image_mod_ts.stdout | int) // 60 }}"

- name: Decide if image is stale
  ansible.builtin.set_fact:
    image_needs_rebuild: "{{ image_age_minutes | int > finalize_provision_image_max_age }}"

- name: Build image if stale
  ansible.builtin.command: wwctl image build almalinux-9
  changed_when: image_needs_rebuild
  when:
    - image_needs_rebuild
    - ( inventory_hostname in groups['sms'] )

- name: Build overlays if image was rebuilt
  ansible.builtin.command: wwctl overlay build
  changed_when: image_needs_rebuild
  when:
    - image_needs_rebuild
    - ( inventory_hostname in groups['sms'] )
# =========================================================
