---
# - name: Setup the foundations
#   hosts:
#     - sms
#   any_errors_fatal: true
#   become: true
#   gather_facts: true
#   roles:
#     # - create_bridge
#     - setup_vms

# - name: Build main server
#   hosts:
#     - sms
#   any_errors_fatal: true
#   become: true
#   gather_facts: true

#   roles:
#     - pre_ohpc
#     - chronyd
#     - setup_ohpc
#     - setup_warewulf
#     - build_compute_images
#     - customize_nodes
#     - build_overlay
#     - hpc_toolchain
#     - setup_modules
#     - finalize_provision

# - name: Post VMs
#   hosts: sms
#   become: true
#   gather_facts: true
#   roles:
#     - post_vms    # TODO: probably this stuff is not needed anymore. In any case, to be joined with setup_vms (the useful bits)

# - name: Setup Nginx gateway
#   hosts: nginx_gateway
#   become: true
#   gather_facts: true
#   roles:
#     - role: nginx
#       tags: nginx

# - name: Setup Slurm
#   hosts:
#     - slurmctld
#     - slurmdbd
#     - login_nodes
#     - computes     # TODO: access to compute nodes has to be tailored for ansible user, probably using a key shared with root
#   become: true
#   gather_facts: true
#   roles:
#     - setup_slurm

# - name: Setup NFS shares
#   hosts:
#     - sms
#     - login_nodes
#     - galaxy_server
#   become: true
#   gather_facts: true
#   roles:
#     - configure_shares

# - name: Setup Login nodes
#   hosts:
#     #- sms     # because of the root scripts
#     - login_nodes
#   become: true
#   gather_facts: true
#   roles:
#     #- fail2ban
#     - customize_puli
#     - ldap

# - name: Install ThinLinc Server
#   hosts: thinlinc_servers
#   roles:
#     - role: thinlinc

- name: Setup Galaxy server
  hosts: galaxy_server
  vars:
    galaxy_config_style: yaml
    galaxy_layout: root-dir
    galaxy_root: /srv/galaxy
    galaxy_commit_id: release_23.0
    galaxy_separate_privileges: true
    galaxy_force_checkout: true
    galaxy_create_user: true
    galaxy_manage_paths: true
    galaxy_manage_systemd: true
    galaxy_user: galaxy
    galaxy_privsep_user: gxpriv
    galaxy_group: galaxy

    # these are custom - not in the GitHub README
    galaxy_user_name: "{{ galaxy_user }}"
    galaxy_venv_dir: "{{ galaxy_root }}/.venv"
    galaxy_tusd_port: 1080
    galaxy_tus_upload_store: /data/tus

    postgresql_objects_users:
      - name: galaxy
        password: null
    postgresql_objects_databases:
      - name: galaxy
        owner: galaxy
    galaxy_config:
      gravity:
        process_manager: systemd
        galaxy_config_file: "{{ galaxy_root }}/config/galaxy.yml"
        galaxy_root: "{{ galaxy_root }}/server"
        galaxy_user: "{{ galaxy_user_name }}"
        virtualenv: "{{ galaxy_venv_dir }}"
        gunicorn:
          # listening options
          bind: "0.0.0.0:8080"
          # performance options
          workers: 2
          # Other options that will be passed to gunicorn
          # This permits setting of 'secure' headers like REMOTE_USER (and friends)
          # https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips
          extra_args: '--forwarded-allow-ips="*"'
          # This lets Gunicorn start Galaxy completely before forking which is faster.
          # https://docs.gunicorn.org/en/stable/settings.html#preload-app
          preload: true
        celery:
          concurrency: 2
          enable_beat: true
          enable: true
          queues: celery,galaxy.internal,galaxy.external
          pool: threads
          memory_limit: 2
          loglevel: DEBUG
        tusd:
          enable: true
          tusd_path: /usr/local/sbin/tusd
          host: 0.0.0.0
          upload_dir: "{{ galaxy_tus_upload_store }}"
        handlers:
          handler:
            processes: 2
            pools:
              - job-handlers
              - workflow-schedulers
      galaxy:
        database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
        static_enabled: true
        admin_users: 
          - Joao.Sequeira@hcemm.eu
          - Alessandra.Vittorini@hcemm.eu
        welcome_url: /static/welcome.html.sample
        # TUS
        galaxy_infrastructure_url: "https://galaxy.hcemm.eu"
        tus_upload_store: "{{ galaxy_tus_upload_store }}"

  pre_tasks:
    - block:
      - name: Create galaxy user and group
        ansible.builtin.group:
          name: "{{ galaxy_group }}"
          state: present

      - name: Create galaxy user
        ansible.builtin.user:
          name: "{{ galaxy_user }}"
          group: "{{ galaxy_group }}"
          state: present
          create_home: true

      - name: Install Dependencies
        ansible.builtin.dnf:
          name:
            - sudo
            - git
            - make
            # - virtualenv        # python3-venv
            - python3-setuptools
            - python3-devel     # python3-dev
            - python3-psycopg2
            - gcc
            - acl
            - gnutls-utils      # gnutls-bin
            - file-devel        # libmagic-dev
            - unzip
            - tar
          state: present

      - name: Install virtualenv
        ansible.builtin.pip:
          name: virtualenv
          executable: pip3

      - name: Symbolic link for virtualenv
        ansible.builtin.file:
          src: /usr/local/bin/virtualenv
          dest: /usr/local/sbin/virtualenv
          state: link

      - name: Install PostgreSQL repository
        ansible.builtin.dnf:
          name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          state: present
          disable_gpg_check: true
      become: true
  roles:
    - role: galaxyproject.postgresql
      become: true
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - role: galaxyproject.galaxy
    - role: galaxyproject.tusd
