---
roles:
  - name: thinlinc-server
    src: https://github.com/cendio/ansible-role-thinlinc-server.git
    scm: git
    version: v1.13

collections:
  - name: community.general
    version: ">=10.6.0"

  - name: community.libvirt
    version: ">=1.4.0"
