---
roles:
  - name: thinlinc-server
    src: https://github.com/cendio/ansible-role-thinlinc-server.git
    scm: git
    version: v1.13

  - src: galaxyproject.galaxy
    version: 0.10.14

  - src: galaxyproject.postgresql
    version: 1.1.2

  - src: galaxyproject.postgresql_objects
    version: 1.2.0

  - src: galaxyproject.miniconda
    version: 0.3.1

collections:
  - name: community.general
    version: ">=10.6.0"

  - name: community.libvirt
    version: ">=1.4.0"

  - name: checkmk.general
    version: "6.0"

  - name: community.mysql
    version: ">=3.15"
