---
- name: Build PULI
  hosts: all
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - common
    - chronyd
    - setup_ohpc
    - setup_warewulf
    - setup_slurm
    - build_compute_images
    - customize_nodes
    - build_overlay
    - finalize_provision
    - setup_modules
    - configure_shares
    - customize_puli
