---
- name: Build PULI
  hosts: all
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - common
    - chronyd
    - setup_ohpc
    - setup_warewulf
    - setup_slurm
    - build_compute_images
    - customize_nodes
    - build_overlay
    - finalize_provision
    - hpc_toolchain
    - customize_puli
    - setup_modules
    - configure_shares

    # - role: thinlinc
    #   vars:
    #     thinlinc_accept_eula: "yes"
    #     thinlinc_version: "4.18.0"
    #     thinlinc_bundle_path: "/root/tl-{{ thinlinc_version }}-server.zip"
    #     thinlinc_autoinstall_dependencies: "yes"
    #     thinlinc_printers: "no"
    #     thinlinc_webaccess_port: 443
    #     thinlinc_webaccess_login_page: ""
    #     thinlinc_webadm_port: 1010
    #     thinlinc_webadm_password: "$6$ef8b0b02b79db5e6$9d6QTuXeVYXFAQmM37UXvHAVUOtMbQBtiUUzq.9qVeY66h.1uyiSxoYNmHm2fOzOV20RIfXaTQm9SGqyx9rJg1"
    #     thinlinc_agent_hostname: "{{ inventory_hostname }}"
