# https://github.com/galaxyproject/ansible-galaxy#best-practice
galaxy_ip: 10.0.150.209
galaxy_port: 8080
galaxy_config_style: yaml
galaxy_layout: root-dir
galaxy_root: /srv/galaxy
galaxy_commit_id: release_26.1
# galaxy_client_use_prebuilt: true     # to wonder if this would be helpful
galaxy_separate_privileges: true
galaxy_force_checkout: true
galaxy_create_user: true
galaxy_manage_paths: true
galaxy_manage_systemd: true
galaxy_manage_cleanup: true         # configure PostgreSQL and Galaxy cleanup tasks
galaxy_user: galaxy
galaxy_privsep_user: gxpriv
galaxy_group: galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_hcemm_logo_url: https://www.hcemm.eu/wp-content/uploads/2020/01/HCEMM_Logo_Slogan_TM_RGB.png
galaxy_venv_dir: "{{ galaxy_root }}/venv"
galaxy_data_dir: /mnt/galaxy/data
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_config_file: "{{ galaxy_config_dir }}/galaxy.yml"    # this might be some default in the role, but who knows, let's be explicit

# TUS
galaxy_tus_upload_store: "{{ galaxy_data_dir }}/tus_uploads"
galaxy_tusd_port: 1080

# PostgreSQL Backups
postgresql_backup_dir: "{{ galaxy_data_dir }}/backups"
postgresql_backup_local_dir: "{{ '~postgres' | expanduser }}/backups"

# CVMFS vars
cvmfs_role: client
galaxy_cvmfs_repos_enabled: config-repo
cvmfs_quota_limit: 500                    # https://training.galaxyproject.org/training-material/topics/admin/tutorials/cvmfs/tutorial.html#tip-what-is-a-good-size-for-this

galaxy_job_config:
  runners:
    local_runner:
      load: galaxy.jobs.runners.local:LocalJobRunner
      workers: 4
  handling:
    assign: ['db-skip-locked']
  execution:
    default: singularity
    environments:
      local_env:
        runner: local_runner
        tmp_dir: true
      singularity:
        runner: local_runner
        singularity_enabled: true
        # Enabling access to the reference data on CVMFS in the container
        singularity_volumes: $defaults,/cvmfs/data.galaxyproject.org:ro
        env:
          # Ensuring a consistent collation environment is good for reproducibility.
          - name: LC_ALL
            value: C
          # The cache directory holds the docker containers that get converted
          - name: APPTAINER_CACHEDIR
            value: /tmp/singularity
          # Apptainer uses a temporary directory to build the squashfs filesystem
          - name: APPTAINER_TMPDIR
            value: /tmp
  tools:
    - class: local # these special tools that aren't parameterized for remote execution - expression tools, upload, etc
      environment: local_env

# https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample
galaxy_config:
  gravity:
    process_manager: systemd
    galaxy_root: "{{ galaxy_root }}/server"
    galaxy_user: "{{ galaxy_user }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    gunicorn:
      # listening options
      bind: "0.0.0.0:8080"
      # performance options
      workers: 2
      # Other options that will be passed to gunicorn
      # This permits setting of 'secure' headers like REMOTE_USER (and friends)
      # https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips
      extra_args: '--forwarded-allow-ips="*"'
      # This lets Gunicorn start Galaxy completely before forking which is faster.
      # https://docs.gunicorn.org/en/stable/settings.html#preload-app
      preload: true
    celery:
      concurrency: 2
      enable_beat: true
      enable: true
      queues: celery,galaxy.internal,galaxy.external
      pool: threads
      memory_limit: 2
      loglevel: DEBUG
    tusd:
      enable: true
      tusd_path: /usr/local/sbin/tusd
      host: 0.0.0.0
      upload_dir: "{{ galaxy_tus_upload_store }}"
    handlers:
      handler:
        processes: 2
        pools:
          - job-handlers
          - workflow-schedulers
  galaxy:
    brand: HCEMM
    logo_src: "{{ galaxy_hcemm_logo_url }}"
    # TODO - complete these URLs with the actual ones for HCEMM
    # support_url: "https://example.org/support"
    # terms_url: "https://example.org/terms-of-service"
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    data_dir: "{{ galaxy_data_dir }}"
    galaxy_infrastructure_url: "http://{{ galaxy_ip }}:{{ galaxy_port }}"
    static_enabled: true
    admin_users:
      - Joao.Sequeira@hcemm.eu
      - Alessandra.Vittorini@hcemm.eu
    welcome_url: /static/welcome.html
    auth_config_file: auth_conf.xml
    tus_upload_store: "{{ galaxy_tus_upload_store }}"
    # CVMFS
    tool_data_table_config_path:
      - /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml
      - /cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml
    dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"
    container_resolvers_config_file: "{{ galaxy_config_dir }}/container_resolvers_conf.yml"

galaxy_extra_dirs:
  - "{{ galaxy_data_dir }}"

# Templates and files to be copied to the Galaxy server. No need for ansible.builtin.template or ansible.builtin.copy tasks, the Galaxy role handles that for us.
# https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html#managing-configuration
galaxy_config_files:
  - src: files/welcome.html
    dest: "{{ galaxy_root }}/server/static/welcome.html"
galaxy_config_templates:
  - src: templates/auth_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/auth_conf.xml"
  - src: templates/themes.yml.j2
    dest: "{{ galaxy_config_dir }}/themes.yml"
  - src: templates/container_resolvers_conf.yml.j2
    dest: "{{ galaxy_config.galaxy.container_resolvers_config_file }}"
  - src: templates/dependency_resolvers_conf.xml.j2
    dest: "{{ galaxy_config.galaxy.dependency_resolvers_config_file }}"
