galaxy_config_style: yaml
galaxy_layout: root-dir
galaxy_root: /srv/galaxy
galaxy_commit_id: release_23.0
galaxy_separate_privileges: true
galaxy_force_checkout: true
galaxy_create_user: true
galaxy_manage_paths: true
galaxy_manage_systemd: true
galaxy_user: galaxy
galaxy_privsep_user: gxpriv
galaxy_group: galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"

galaxy_tus_upload_store: /data/tus
galaxy_tusd_port: 1080
# galaxy_tus_upload_store: /mnt/galaxy/tus_uploads
# galaxy_base_dir: /home/{{ galaxy_user }}/galaxy
# galaxy_tus_exec_dir: /home/{{ galaxy_user }}/bin/tusd
# galaxy_config_dir: "{{ galaxy_base_dir }}/config"

galaxy_config:
  gravity:
    process_manager: systemd
    galaxy_root: "{{ galaxy_root }}/server"
    galaxy_user: "{{ galaxy_user }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    gunicorn:
      # listening options
      bind: "0.0.0.0:8080"
      # performance options
      workers: 2
      # Other options that will be passed to gunicorn
      # This permits setting of 'secure' headers like REMOTE_USER (and friends)
      # https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips
      extra_args: '--forwarded-allow-ips="*"'
      # This lets Gunicorn start Galaxy completely before forking which is faster.
      # https://docs.gunicorn.org/en/stable/settings.html#preload-app
      preload: true
    celery:
      concurrency: 2
      enable_beat: true
      enable: true
      queues: celery,galaxy.internal,galaxy.external
      pool: threads
      memory_limit: 2
      loglevel: DEBUG
    handlers:
      handler:
        processes: 2
        pools:
          - job-handlers
          - workflow-schedulers
  galaxy:
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    static_enabled: true
    admin_users:
      - Joao.Sequeira@hcemm.eu
      - Alessandra.Vittorini@hcemm.eu
    welcome_url: /static/welcome.html
