# sss_cache -E
- name: Clear SSSD cache
  ansible.builtin.command: sss_cache -E
  changed_when: true
  notify: Restart sssd

# systemctl restart sssd
- name: Restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted
    enabled: true
