---
- name: Initial LDAP database construction and configuration
  when:
    - inventory_hostname in groups['ldap_server']
  block:
    # hostnamectl set-hostname freeipa.hcemm.eu
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ ldap_server_fqdn }}"

    # setup minimal /etc/hosts
    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ldap_vm_ip }} {{ ldap_server_fqdn }} {{ ldap_server_fqdn.split('.')[0] }}"    # e.g., "10.0.150.203  freeipa.hcemm.eu freeipa"
        state: present

    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - ipa-server
          - ipa-server-dns
        state: present

    # firewall-cmd --add-port= --permanent
    - name: Open firewall ports for FreeIPA
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - 80/tcp    # HTTP
        - 443/tcp   # HTTPS
        - 389/tcp   # LDAP
        - 636/tcp   # LDAPS
        - 88/tcp    # Kerberos
        - 464/tcp   # Kerberos Password Change
        - 53/tcp    # bind
        - 88/udp    # Kerberos
        - 464/udp   # Kerberos Password Change
        - 53/udp    # bind
        - 123/udp   # ntp

    - name: Install FreeIPA server (NON-interactive)
      ansible.builtin.command: >
        ipa-server-install
        --hostname={{ ldap_server_fqdn }}
        --domain={{ ldap_domain }}
        --realm={{ ldap_realm }}
        --ds-password='{{ ldap_admin_password_raw }}'
        --admin-password='{{ ldap_admin_password_raw }}'
        --mkhomedir
        --unattended
      args:
        creates: /etc/ipa/default.conf    # confirm if this file is actually created, and didn't exist before


- name: Configure LDAP for other hosts
  when:
    - false     # inventory_hostname in groups['galaxy_server'] or inventory_hostname in groups['login_nodes']
  block:
    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - openldap-servers
          - python-ldap
          - sssd-ldap
        state: present

    - name: Copy CA certificate
      ansible.builtin.copy:
        src: ca.crt
        dest: "{{ item }}/ca.crt"
        owner: ldap
        group: ldap
        mode: "0644"
      loop:
        - /etc/openldap/certs
        - /etc/pki/ca-trust/source/anchors

    - name: Update CA trust store
      ansible.builtin.command: update-ca-trust extract
      args:
        creates: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt

    - name: Configure LDAP client
      ansible.builtin.lineinfile:
        path: /etc/openldap/ldap.conf
        line: "TLS_CACERT {{ ldap_tls_cacert_path }}"

    - name: Deploy sssd.conf
      ansible.builtin.template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        mode: '0600'
      notify: Restart sssd

    - name: Ensure 'sss' is present in passwd, shadow and group lines in /etc/nsswitch.conf
      ansible.builtin.replace:
        path: /etc/nsswitch.conf
        regexp: '^(passwd|shadow|group):(?!.*\bsss\b)(\s+)(.*)$'    # find confs that do not have 'sss' yet and add it
        replace: '\1:\2sss \3'

    - name: Assert pam_sss is enabled in system-auth
      ansible.builtin.command: grep "auth       sufficient pam_sss.so forward_pass" /etc/pam.d/system-auth
      register: pam_sss_grep
      changed_when: false

    - name: Assert pam_sss is enabled in system-auth
      ansible.builtin.debug:
        var: pam_sss_grep

    - name: Ensure authselect uses sssd     # this connects PAM to SSSD
      ansible.builtin.command: authselect select sssd with-mkhomedir --force
      changed_when: true
      when: pam_sss_grep.stdout | length == 0

    - name: Ensure google_authenticator is after pam_sss in sshd
      community.general.pamd:
        name: sshd
        type: auth
        control: sufficient
        module_path: pam_sss.so
        new_type: auth
        new_control: required
        new_module_path: pam_google_authenticator.so
        module_arguments: "secret=\\${HOME}/.google_authenticator nullok"
        state: after

    - name: Ensure SSSD is used for account
      community.general.pamd:
        name: "{{ item }}"
        type: account
        control: required
        module_path: pam_unix.so
        new_type: account
        new_control: sufficient
        new_module_path: pam_sss.so
        state: after
      loop:
        - system-auth
        - password-auth
