---
- name: Copy configuration files into /etc      # Never mount this. There are host specific files here (e.g. /etc/hostname), SELinux breaks, etc.
  ansible.builtin.copy:
    src: system_root/etc
    dest: /etc
    owner: root
    group: root
    mode: "0644"

- name: Copy user executables into /usr/local/bin
  ansible.builtin.copy:
    src: usr/local/bin
    dest: /usr/local
    owner: root
    group: root
    mode: "0755"

- name: Copy root executables into /root/bin
  ansible.builtin.copy:
    src: root/bin
    dest: /root
    owner: root
    group: root
    mode: "0700"

- name: Copy lmod.sh
  ansible.builtin.copy:
    src: /etc/profile.d/lmod.sh
    dest: /etc/profile.d/lmod.sh
    owner: root
    group: root
    mode: "0755"

- name: Add cron job to check 2FA users hourly
  ansible.builtin.cron:
    name: "Check 2FA users"
    minute: "0"
    job: "/root/bin/enforce-2fa.sh"

#   dnf -y install ohpc-slurm-client
#   systemctl enable munge
#   systemctl enable slurmd
#   Add Network Time Protocol (NTP) support
#   dnf -y install chrony
#   Include modules user environment
#   dnf -y install lmod-ohpc
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - ohpc-slurm-client
      - chrony
      # lua must be installed for lmod to work
      - lua
      - lua-posix
      - lua-filesystem
      - tcl
    state: present

- name: Configure limits.conf
  ansible.builtin.template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: "0644"
