---
- name: Copy configuration files into /etc      # Never mount this. There are host specific files here (e.g. /etc/hostname), SELinux breaks, etc.
  ansible.builtin.copy:
    src: system_root/etc/
    dest: /etc
    owner: root
    group: root
    mode: "0644"
    force: true                                 # we want to overwrite files in /etc with our versions, even if they already exist

- name: Copy user executables into /usr/local/bin
  ansible.builtin.copy:
    src: usr/local/bin/
    dest: /usr/local
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Copy root executables into /root/bin
  ansible.builtin.copy:
    src: root/bin/
    dest: /root
    owner: root
    group: root
    mode: "0700"
    force: true

- name: Copy lmod.sh
  ansible.builtin.copy:
    src: /etc/profile.d/lmod.sh
    dest: /etc/profile.d/lmod.sh
    owner: root
    group: root
    mode: "0755"
    force: true

- name: Add cron job to check 2FA users hourly
  ansible.builtin.cron:
    name: "Check 2FA users"
    minute: "0"
    job: "/root/bin/enforce-2fa.sh"

# dnf install -y install http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm
- name: Install OpenHPC repo
  ansible.builtin.dnf:
    name: http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: true     # started complaining couldn't find the GPG key, it was fine before. If found, we can make a task with `ansible.builtin.rpm_key`

#   dnf -y install ohpc-slurm-client
#   systemctl enable munge
#   systemctl enable slurmd
#   Add Network Time Protocol (NTP) support
#   dnf -y install chrony
#   Include modules user environment
#   dnf -y install lmod-ohpc
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - ohpc-slurm-client
      - chrony
      # lua must be installed for lmod to work
      - lua
      - lua-posix
      - lua-filesystem
      - tcl
    state: present

- name: Configure limits.conf
  ansible.builtin.template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: "0644"

# tr -d '\r' < /etc/logrotate.d/slurm > /etc/logrotate.d/slurm
- name: Configure logrotate for slurm
  ansible.builtin.shell: |
    set -o pipefail
    tr -d '\r' < /etc/logrotate.d/slurm > /etc/logrotate.d/slurm
  changed_when: false
