---
# dnf -y install dnf-plugins-core
- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  when: inventory_hostname in groups['guacamole_server']

# dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
- name: Install Docker CE repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  when: inventory_hostname in groups['guacamole_server']

- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - libxcrypt-compat    # required by docker-compose
    state: present
  notify: Start and enable Docker service
  when: inventory_hostname in groups['guacamole_server']


# curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- name: Install docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: inventory_hostname in groups['guacamole_server']

- name: Create Guacamole configuration directories
  ansible.builtin.file:
    path: /opt/guacamole/{{ item }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - extensions
    - init
  when: inventory_hostname in groups['guacamole_server']

- name: Deploy Guacamole docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/guacamole/docker-compose.yml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['guacamole_server']
  notify: Start Guacamole container

# mkdir ./extensions/
- name: Create Guacamole extensions directory
  ansible.builtin.file:
    path: /opt/guacamole/extensions
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname in groups['guacamole_server']

- name: Allow 8080 from nginx gateway
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="10.0.150.211" port protocol="tcp" port="8080" accept
    permanent: true
    state: enabled
    immediate: true
  when: inventory_hostname in groups['guacamole_server']

- name: Deploy HAProxy Guacamole config   # don't need include
  ansible.builtin.template:
    src: guacamole.cfg.j2
    dest: /etc/haproxy/conf.d/guacamole.cfg
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['sms']
  notify: Restart HAProxy

- name: Install XRDP on login nodes
  ansible.builtin.dnf:
    name:
      - xrdp
      - xorgxrdp
      - "@Xfce"     # dnf groupinstall "Xfce"
    state: present
  when: inventory_hostname in groups['login_nodes']

- name: Deploy XRDP main configuration on login nodes
  ansible.builtin.template:
    src: xrdp.ini.j2
    dest: /etc/xrdp/xrdp.ini
    owner: root
    group: root
    mode: "0644"
    backup: true
  when: inventory_hostname in groups['login_nodes']
  notify: Restart XRDP services

- name: Deploy XRDP Xfce start script on login nodes
  ansible.builtin.template:
    src: xrdp-startxfce4.sh.j2
    dest: /usr/local/bin/xrdp-startxfce4.sh
    owner: root
    group: root
    mode: "0755"
    backup: true
  when: inventory_hostname in groups['login_nodes']
  notify: Restart XRDP services

- name: Deploy XRDP sesman PAM configuration on login nodes
  ansible.builtin.template:
    src: xrdp-sesman.pam.j2
    dest: /etc/pam.d/xrdp-sesman
    owner: root
    group: root
    mode: "0644"
    backup: true
  when: inventory_hostname in groups['login_nodes']
  notify: Restart XRDP services

- name: Remove generic RDP service exposure on login nodes
  ansible.posix.firewalld:
    service: rdp
    permanent: true
    state: disabled
    immediate: true
  when: inventory_hostname in groups['login_nodes']

- name: Remove generic XRDP port exposure on login nodes
  ansible.posix.firewalld:
    port: "{{ xrdp_port }}/tcp"
    permanent: true
    state: disabled
    immediate: true
  when: inventory_hostname in groups['login_nodes']

- name: Allow XRDP only from Guacamole server on login nodes
  ansible.posix.firewalld:
    rich_rule: >-
      rule family="ipv4"
      source address="{{ hostvars[groups['guacamole_server'][0]]['ansible_host'] }}"
      port protocol="tcp" port="{{ xrdp_port }}"
      accept
    permanent: true
    state: enabled
    immediate: true
  when: inventory_hostname in groups['login_nodes']

# copy guacamole_key private key to guacamole
- name: Copy Guacamole private key to guacamole VM
  ansible.builtin.copy:
    src: guacamole_key
    dest: /opt/guacamole/guacamole_key
    owner: root
    group: root
    mode: "0600"
    decrypt: true
  when: inventory_hostname in groups['guacamole_server']

# copy guacamole_key public key to login nodes
- name: Copy Guacamole public key to login nodes
  ansible.builtin.copy:
    src: guacamole_key.pub
    dest: /etc/ssh/guacamole_key.pub
    owner: root
    group: root
    mode: "0644"
    decrypt: true
  when: inventory_hostname in groups['login_nodes']

# AuthorizedKeysFile .ssh/authorized_keys /etc/ssh/guacamole_key.pub
- name: Configure SSH to allow Guacamole public key authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AuthorizedKeysFile'
    line: 'AuthorizedKeysFile .ssh/authorized_keys /etc/ssh/guacamole_key.pub'
    state: present
  when: inventory_hostname in groups['login_nodes']
  notify: Restart SSH service

# echo "exec startxfce4" > ~/.Xclients
- name: Configure Xfce as default session for XRDP
  ansible.builtin.copy:
    dest: /etc/skel/.Xclients
    content: "exec startxfce4\n"
    owner: root
    group: root
    mode: "0755"
  when: inventory_hostname in groups['sms']           # can't be done on login_nodes cause this is mounted home dir from SMS

- name: Ensure current users have .Xclients for Xfce
  ansible.builtin.copy:
    dest: "/home/{{ item.username }}/.Xclients"
    content: "exec startxfce4\n"
    owner: "{{ item.username }}"
    group: "{{ item.groups[0] }}"
    mode: "0755"
    force: false
  loop: "{{ ldap_users }}"
  when: inventory_hostname in groups['sms']
