---
- name: Check if service is installed
  ansible.builtin.command: >
    wwctl image exec --build=false {{ image }} rpm -q {{ service }}
  register: service_check
  changed_when: false
  failed_when: false

- name: Install service
  ansible.builtin.command: >
    wwctl image exec --build=false {{ image }} dnf -y install {{ service }}
  when: service_check.rc != 0
  changed_when: service_check.rc != 0

- name: Enable service inside image - {{ service }}
  ansible.builtin.command: >
    wwctl image exec --build=false {{ image }} systemctl enable {{ service }}
  changed_when: true   # systemctl doesn't mark change
