---
# wwctl image import docker://ghcr.io/warewulf/warewulf-almalinux:9 almalinux-9 --syncuser
- name: Check if Alma Linux image is already imported
  ansible.builtin.command: >
    wwctl image show almalinux-9
  register: alma_image_present
  changed_when: false
  failed_when: false    # wwctl will report "ERROR: almalinux-91 is not a valid image if image is not present"
  when:
    - inventory_hostname in groups['sms']

- name: Import Alma Linux image
  ansible.builtin.command: >
    wwctl image import docker://ghcr.io/warewulf/warewulf-almalinux:9 almalinux-9 --syncuser
  changed_when: alma_image_present.rc != 0
  when:
    - inventory_hostname in groups['sms']
    - "'/warewulf/chroots/almalinux-9/rootfs' not in alma_image_present.stdout"

# wwctl image exec --build=false almalinux-9 /bin/bash <<- EOF
#   dnf -y install http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm
#   dnf -y update
# EOF
- name: Check if OpenHPC repo is installed inside image
  ansible.builtin.shell: >
    set -o pipefail; echo 'rpm -q ohpc-release' | wwctl image exec --build=false almalinux-9 /bin/bash
  register: ohpc_repo_check
  changed_when: false
  failed_when: false    # warewulf will fail with "package ohpc-release is not installed (exit code 127)"
  when:
    - inventory_hostname in groups['sms']

- name: Install OpenHPC repo inside image
  ansible.builtin.shell: >
    set -o pipefail; echo 'dnf -y install http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm; dnf -y update' |
    wwctl image exec --build=false almalinux-9 /bin/bash
  changed_when: ohpc_repo_check.rc != 0
  when:
    - ( "package ohpc-release is not installed" in ohpc_repo_check.stdout )
    - inventory_hostname in groups['sms']

# export CHROOT=$(wwctl image show almalinux-9)
- name: Get Warewulf chroot path for almalinux-9
  ansible.builtin.command: wwctl image show almalinux-9
  register: base_chroot
  changed_when: false

# wwctl image exec --build=false almalinux-9 /bin/bash <<- EOF
#   dnf -y install ohpc-base-compute
# EOF
# wwctl image exec --build=false almalinux-9 /bin/bash <<- EOF
#   Add Slurm client support meta-package and enable munge and slurmd
#   dnf -y install ohpc-slurm-client
#   systemctl enable munge
#   systemctl enable slurmd
#   Add Network Time Protocol (NTP) support
#   dnf -y install chrony
#   Include modules user environment
#   dnf -y install lmod-ohpc
# EOF
- name: Install required packages into Warewulf image
  ansible.builtin.include_tasks: install_pkg_on_image.yml
  vars:
    image: almalinux-9
    pkg: "{{ item }}"
  loop:
    - ohpc-base-compute
    - ohpc-slurm-client
    - chrony
    - lmod-ohpc
  when:
    - inventory_hostname in groups['sms']

- name: Enable services inside Warewulf image
  ansible.builtin.shell: >
    set -o pipefail; echo 'systemctl enable {{ item }}' | wwctl image exec --build=false almalinux-9 /bin/bash
  changed_when: true   # systemctl doesn't mark change - and I could check for "Created symlink..." but it would be a bit messy
  loop:
    - munge
    - slurmd
  when:
    - inventory_hostname in groups['sms']
