---
# hostnamectl set-hostname scc-cpu01-10g.cluster.hcemm.eu
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ master_hostname | lower }}.{{ cluster_domain }}"

# dnf install -y NetworkManager
- name: Ensure NetworkManager is installed
  ansible.builtin.package:
    name: NetworkManager
    state: present

# systemctl enable --now NetworkManager
- name: Ensure NetworkManager is enabled and running
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
    state: started

# nmcli connection modify br0 \
#   ipv4.addresses 10.0.150.101/24 \
#   ipv4.gateway 10.0.150.254 \
#   ipv4.dns 10.0.150.203 \
#   ipv4.dns-search cluster.hcemm.eu \
#   ipv4.ignore-auto-dns yes \
#   ipv4.method manual \
#   bridge.stp yes \
#   bridge.priority 32768 \
#   connection.autoconnect yes
- name: Configure bridge interface
  community.general.nmcli:
    conn_name: "{{ bridge_name }}"
    ifname: "{{ bridge_name }}"
    type: bridge
    ip4:
      - "{{ sms_ip }}/24"
    gw4: "{{ sms_gateway }}"
    dns4:
      - "{{ bridge_dns }}"
    dns4_search:
      - "{{ cluster_domain }}"
    dns4_ignore_auto: true
    method4: manual
    stp: true
    priority: 32768
    autoconnect: true
    state: present
  notify: Activate SMS network

# nmcli connection add type bond \
#   con-name bond0 \
#   ifname bond0 \
#   bond.options "mode=802.3ad,miimon=100,xmit_hash_policy=layer3+4"

# nmcli connection modify bond0 \
#   connection.master br0 \
#   connection.slave-type bridge \
#   ipv4.method disabled \
#   ipv6.method disabled \
#   connection.autoconnect yes
- name: Configure LACP bond
  community.general.nmcli:
    conn_name: "{{ bond_name }}"
    ifname: "{{ bond_name }}"
    type: bond
    mode: "{{ bond_mode }}"
    miimon: "{{ bond_miimon }}"
    xmit_hash_policy: "{{ bond_xmit_hash_policy }}"
    master: "{{ bridge_name }}"
    slave_type: bridge
    method4: disabled
    method6: disabled
    autoconnect: true
    state: present
  notify: Activate SMS network

# nmcli connection add type ethernet \
#   con-name <interface> \
#   ifname <interface> \
#   master bond0

# nmcli connection modify <interface> \
#   connection.master bond0 \
#   connection.slave-type bond \
#   ipv4.method disabled \
#   ipv6.method disabled \
#   connection.autoconnect yes
- name: Configure physical interfaces as bond members
  community.general.nmcli:
    conn_name: "{{ item }}"
    ifname: "{{ item }}"
    type: ethernet
    master: "{{ bond_name }}"
    slave_type: bond
    method4: disabled
    method6: disabled
    autoconnect: true
    state: present
  loop: "{{ bond_members }}"
  notify: Activate SMS network
