login_nodes_limits:
  memory_high: 1500M
  memory_max: 2G
  tasks_max: 512
  cpu_quota: 200%           # two cpus max
  cpu_weight: 100
  cpu_time_soft: 7200       # 2 hours max
  cpu_time_hard: 10800      # 3 hours max
