---
- name: Copy system_root into /
  ansible.builtin.copy:
    src: system_root/
    dest: /
    owner: root
    group: root
    mode: "0644"
  when:
    - inventory_hostname in groups['login_nodes']

- name: Copy user executables into /usr/local/bin
  ansible.builtin.copy:
    src: usr/local/bin
    dest: /usr/local
    owner: root
    group: root
    mode: "0755"
  when:
    - inventory_hostname in groups['login_nodes']

- name: Copy root executables into /root/bin
  ansible.builtin.copy:
    src: root/bin
    dest: /root
    owner: root
    group: root
    mode: "0700"

- name: Add cron job to check 2FA users hourly
  ansible.builtin.cron:
    name: "Check 2FA users"
    minute: "0"
    job: "/root/bin/enforce-2fa.sh"
  when:
    - inventory_hostname in groups['login_nodes']
