---
# defaults file for kvm_provision
setup_vms_base_image_name: AlmaLinux-9.8-x86_64-minimal.iso
setup_vms_base_image_url: "https://repo.almalinux.org/almalinux/9/isos/x86_64/{{ setup_vms_base_image_name }}"
setup_vms_base_image_sha: 7762a4b45a66235726db145a573658964bf77bf7b9bc1c018afe86a4cf37cc2e
setup_vms_cleanup_tmp: false
setup_vms_kickstart_port: 9876
