---
# defaults file for kvm_provision
setup_vms_base_image_name: AlmaLinux-9-latest-x86_64-minimal.iso
setup_vms_base_image_url: "https://repo.almalinux.org/almalinux/9/isos/x86_64/{{ setup_vms_base_image_name }}"
setup_vms_base_image_sha: d51ed22cf272a0f30fcf55579d2748ff6ee1fddd6e36ba728cb386b933ceb7fc
setup_vms_cleanup_tmp: false
setup_vms_kickstart_port: 9876
