- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Start Guacamole container
  ansible.builtin.shell: |
    cd /opt/guacamole
    docker-compose up -d
  changed_when: true

- name: Restart HAProxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

- name: Restart SSH service
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart XRDP services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - xrdp
    - xrdp-sesman
  failed_when: false
