- name: Restorecon venv bin
  ansible.builtin.command: restorecon -Rv /mnt/pulsar/venv/bin
  changed_when: false

- name: Update CA trust
  ansible.builtin.command: update-ca-trust extract
  changed_when: true

- name: Restart Pulsar
  ansible.builtin.systemd:
    name: pulsar
    state: restarted

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
