- name: Run command and check output
  ansible.builtin.command: "{{ cmd }}"
  register: command_output
  changed_when: false

- name: Check if pattern is found in command output
  ansible.builtin.set_fact:
    output_match_found: "{{ command_output.stdout_lines | select('match', pattern) | list | length > 0 }}"
