# This playbook checks if specific strings are present in the output of a command.
# It returns one value of "output_match_found" as true if all patterns are found, and false otherwise.
- name: Run command and capture output
  ansible.builtin.command: "{{ cmd }}"
  register: command_output
  changed_when: false

- name: Initialize output_match_found to true
  ansible.builtin.set_fact:
    output_match_found: true
    patterns_not_found: []

- name: Check each literal pattern in command output
  vars:
    pattern_found: "{{ command_output.stdout.find(item) != -1 }}"
  ansible.builtin.set_fact:
    output_match_found: false
    patterns_not_found: "{{ patterns_not_found + [item] }}"
  when: not pattern_found
  loop: "{{ patterns }}"
