- name: Run command and capture output
  ansible.builtin.command: "{{ cmd }}"
  register: command_output
  changed_when: false

- name: Check all patterns are present in output
  ansible.builtin.set_fact:
    output_match_found: >-
      {{
        patterns | map('regex_search', command_output.stdout, multiline=True) | list | select('equalto', None) | list | length == 0
      }}