---
- name: Check if package is installed in Warewulf image - {{ pkg }}
  ansible.builtin.shell: >
    set -o pipefail; echo 'rpm -q {{ pkg }}' | wwctl image exec --build=false {{ image }} /bin/bash
  register: "pkg_check"
  changed_when: false
  failed_when: false

- name: Install package into Warewulf image - {{ pkg }}
  ansible.builtin.shell: >
    set -o pipefail; echo 'dnf -y install {{ pkg }}' | wwctl image exec --build=false {{ image }} /bin/bash
  when: lookup('vars', 'pkg_check').rc != 0
  changed_when: lookup('vars', 'pkg_check').rc != 0
