OUTPUT=ISO
BACKUP=NETFS

HOSTNAME="$(hostname -s)"

BACKUP_PROG_EXCLUDE=(
  /proc/*
  /sys/*
  /dev/*
  /run/*
  /tmp/*
  /var/tmp/*
  /var/cache/*
  /mnt/*
  /media/*
  /lost+found
  /playground/*
  /scratch/*
  /common/*
)

BACKUP_URL=file:///mnt/root-admin/rear-backup