sm_spack_version: "0.23.1"
sm_spack_gcc: "11.5.0"
sm_spack_packages:
  - bwa
  - sratoolkit
  - picard
  - samtools
  - py-macs3
  - bedtools2
  - py-pandas
  - miniconda3
  - apptainer
  - py-multiqc
  - seqkit
  - cd-hit
