---
# dnf install -y install http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm
- name: Install OpenHPC repo
  ansible.builtin.dnf:
    name: http://repos.openhpc.community/OpenHPC/3/EL_9/x86_64/ohpc-release-3-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: true     # started complaining couldn't find the GPG key, it was fine before. If found, we can make a task with `ansible.builtin.rpm_key`

- name: Install Spack
  ansible.builtin.dnf:
    name: spack-ohpc
    state: present

- name: Set Spack module management
  ansible.builtin.replace:
    path: /opt/ohpc/pub/apps/spack/{{ setup_modules_spack_version }}/etc/spack/defaults/modules.yaml
    regexp: 'enable:\s*\["tcl"\]'
    replace: 'enable: ["lmod"]'

# module use /opt/ohpc/pub/modulefiles/site
- name: Ensure modules directories to MODULEPATH
  ansible.builtin.lineinfile:
    path: /etc/profile.d/lmod.sh
    line: 'export MODULEPATH={{ item }}:$MODULEPATH'
    state: present
  loop:
    - /opt/ohpc/pub/modulefiles/site        # custom modules (e.g., Miniconda3)
    - /opt/ohpc/pub/apps/spack/{{ setup_modules_spack_version }}/share/spack/lmod/gcc/{{ setup_modules_spack_gcc }}   # Spack modules

- name: Install Spack packages
  ansible.builtin.shell: >
    source /etc/profile.d/lmod.sh; ml spack;
    spack find {{ item }} || spack install {{ item }} gcc@{{ setup_modules_spack_gcc }}   # `spack find` returns 0 if package is installed, 1 otherwise
  loop: "{{ setup_modules_spack_packages }}"
  register: spack_result
  changed_when: "'Installing' in spack_result.stdout"
  when:
    - setup_modules_spack_packages is defined
    - setup_modules_spack_packages | length > 0
  notify: Refresh Spack modules

- name: Download Miniconda3
  ansible.builtin.get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: /tmp/Miniconda3-latest-Linux-x86_64.sh
    mode: '0755'

- name: Install Miniconda3
  ansible.builtin.shell: >
    /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3
  args:
    creates: /opt/miniconda3/bin/conda

- name: Copy Miniconda3 modulefile
  ansible.builtin.copy:
    src: miniconda3.lua
    dest: /opt/ohpc/pub/modulefiles/site/miniconda3/{{ setup_modules_miniconda3_version }}.lua
    owner: root
    group: root
    mode: '0644'


