---
- name: Manage LDAP users
  ansible.builtin.import_tasks: ldap_user.yml
  when: manage_ldap_users | default(true) | bool
  tags:
    - users
    - ldap_user

- name: Manage Slurm users
  ansible.builtin.import_tasks: slurm_user.yml
  when: manage_slurm_users | default(true) | bool
  tags:
    - users
    - slurm_user