---
# nmcli conn mod enp1s0 ipv4.dns 10.0.150.203
# nmcli conn mod enp1s0 ipv4.dns-search cluster.hcemm.eu
- name: Configure DNS and search domains with nmcli
  community.general.nmcli:
    conn_name: enp1s0
    state: present
    dns4:
      - "{{ ldap_vm_ip }}"
    dns4_search:
      - "{{ ldap_domain }}"
