---
# Disable firewall
# systemctl disable --now firewalld
- name: Disable firewall
  ansible.builtin.service:
    name: firewalld
    enabled: false
  when:
    ( inventory_hostname in groups['sms'] )

# timedatectl set-timezone Europe/Budapest
- name: Set timezone
  community.general.timezone:
    name: Europe/Budapest
  when:
    ( inventory_hostname in groups['sms'] or inventory_hostname in groups['computes'] )

# ip link set dev ${sms_eth_internal} up
# ip address add ${sms_ip}/${internal_netmask} broadcast + dev ${sms_eth_internal}
- name: Set internal network interface address
  community.general.nmcli:
    conn_name: "{{ sms_eth_internal }}"
    ip4: "{{ sms_ip }}/{{ '24' if internal_netmask == '255.255.255.0' else '32' }}"
    state: present
  when:
    ( inventory_hostname in groups['sms'] )

# sysctl -w net.ipv4.ip_forward=1 - so computes have internet
- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true
  when:
    ( inventory_hostname in groups['sms'] )

# systemctl enable chronyd.service
- name: Enable chronyd service
  ansible.builtin.service:
    name: chronyd
    enabled: true
  when:
    ( inventory_hostname in groups['sms'] )

# echo "local stratum 10" >> /etc/chrony.conf
# echo "server ${ntp_server}" >> /etc/chrony.conf
# echo "allow all" >> /etc/chrony.conf
- name: Configure chrony
  ansible.builtin.lineinfile:
    dest: /etc/chrony.conf
    line: "{{ item }}"
  loop:
    - "local stratum 10"
    - "server {{ ntp_server }}"
    - "allow all"
  when:
    ( inventory_hostname in groups['sms'] )

# systemctl restart chronyd
- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
  when:
    ( inventory_hostname in groups['sms'] )
