---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false
