---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded
