---
# According to the instructions at https://www.redhat.com/en/blog/protect-systems-fail2ban
- name: Install fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present

- name: Copy fail2ban base configuration file into place
  ansible.builtin.copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "644"
    force: false
  notify:
    - Restart fail2ban

- name: Copy SSHD jail configuration
  ansible.builtin.copy:
    src: sshd.local
    dest: /etc/fail2ban/jail.d/sshd.local
    owner: root
    group: root
    mode: "644"
    force: false
  notify:
    - Restart fail2ban
  when:
    - inventory_hostname in groups['sms']

- name: Ensure fail2ban is configured to ignore specific IPs
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/jail.local
    regexp: '^#ignoreip ='
    line: "ignoreip = {{ fail2ban_ignoreips | join(' ') }}"
  notify:
    - Restart fail2ban

- name: Activate nginx probes jail
  ansible.builtin.copy:
    src: nginx-probes.local.j2
    dest: /etc/fail2ban/jail.d/nginx-probes.local
    owner: root
    group: root
    mode: "644"
  notify:
    - Restart fail2ban
  when:
    - inventory_hostname in groups['nginx_gateway']

- name: Copy custom fail2ban filter definitions
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/filter.d/{{ item }}
    owner: root
    group: root
    mode: "644"
  loop:
    - nginx-actuator.conf
    - nginx-docker-actor.conf
    - nginx-lfi-rce.conf
    - nginx-php-exploit.conf
    - nginx-scanner.conf
  notify:
    - Restart fail2ban
  when:
    - inventory_hostname in groups['nginx_gateway']

- name: Enable nginx jails in jail.local
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Enable nginx jails"
    block: |
      [nginx-http-auth]
      enabled=true
      [nginx-limit-req]
      enabled=true
      [nginx-botsearch]
      enabled=true
      [nginx-bad-request]
      enabled=true
      [nginx-forbidden]
      enabled=true
  notify:
    - Restart fail2ban
  when:
    - inventory_hostname in groups['nginx_gateway']
