---
# Disable firewall
# systemctl disable --now firewalld
- name: Disable firewall
  ansible.builtin.service:
    name: firewalld
    enabled: false
  when:
    ( inventory_hostname in groups['sms'] )
