---
# Disable firewall
# systemctl disable --now firewalld
- name: Disable firewall
  ansible.builtin.service:
    name: firewalld
    enabled: false
  when:
    ( inventory_hostname in groups['sms'] )

# timedatectl set-timezone Europe/Budapest
- name: Set timezone
  ansible.general.timezone:
    name: Europe/Budapest
  when:
    ( inventory_hostname in groups['sms'] or inventory_hostname in groups['computes'] )

# ip link set dev ${sms_eth_internal} up

- name: Set internal network interface up
  community.general.nmcli:
    conn_name: {{ sms_eth_internal }}
    state: up
  when:
    ( inventory_hostname in groups['sms'] )

# ip address add ${sms_ip}/${internal_netmask} broadcast + dev ${sms_eth_internal}
- name: Set internal network interface address
  community.general.nmcli:
    conn_name: {{ sms_eth_internal }}
    ip4: "{{ sms_ip }}/{{ internal_netmask }}"
    state: present
  when:
    ( inventory_hostname in groups['sms'] )

