users_partitions: >-
  {{
      ['cpu']
      +
      ('gpu' in item.slurm_partitions | ternary(['gpu'],[]))
      +
      ('highmem' in item.slurm_partitions | ternary(['highmem'],[]))
  }}

ldap_user_auth_type:
  - otp
