---
# cp /etc/slurm/slurm.conf.ohpc /etc/slurm/slurm.conf
# cp /etc/slurm/cgroup.conf.example /etc/slurm/cgroup.conf
# perl -pi -e "s/SlurmctldHost=\S+/SlurmctldHost=${sms_name}/" /etc/slurm/slurm.conf
- name: Copy the files from the template directory
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/slurm/{{ item }}"
    mode: "{{ '0600' if item in ['slurmdbd.conf', 'acct_gather.conf'] else '0644' }}"
  loop:
    - slurm.conf
    - slurmdbd.conf
    - cgroup.conf
    - acct_gather.conf
    - topology.conf
  when:
    - ( inventory_hostname in groups['login_nodes'] ) or
      ( inventory_hostname in groups['slurmctld'] )

- name: Copy Prolog and Epilog executable scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/slurm/{{ item }}"
    mode: '0755'
  loop:
    - epilog.sh

# systemctl enable --now munge
- name: Enable and start munge service
  ansible.builtin.systemd:
    name: munge
    enabled: true
    state: started
  when:
    - ( inventory_hostname in groups['login_nodes'] ) or
      ( inventory_hostname in groups['slurmctld'] )

# systemctl enable --now slurmctld
- name: Enable and start slurmctld service
  ansible.builtin.systemd:
    name: slurmctld
    enabled: true
    state: started
  when:
    - ( inventory_hostname in groups['sms'] )
    - env == 'production'

- name: Enable and start slurmd service
  ansible.builtin.systemd:
    name: slurmd
    enabled: true
    state: started
  when:
    - ( inventory_hostname in groups['computes'] )
    - env == 'production'

# pdsh -w $(IFS=','; echo "${c_name[*]}") "/usr/sbin/nhc-genconf -H '*' -c -" | dshbak -c
- name: Generate NHC configuration on compute nodes
  ansible.builtin.shell: |
    set -o pipefail
    /usr/sbin/nhc-genconf -H '*' -c - | dshbak -c
  args:
    creates: /etc/nhc/nhc.conf
  when:
    - ( inventory_hostname in groups['computes'] )
    - env == 'production'

- name: Create Slurm log directory    # as configured in slurm.conf
  ansible.builtin.file:
    path: /var/log/slurm
    state: directory
    mode: '0755'
  when: ( inventory_hostname in groups['computes'] )
