# Generic scanner patterns (phpunit, common php probe paths)
[Definition]
failregex = <HOST> -.*"(GET|POST).*(phpunit|eval-stdin|/vendor/phpunit|/vendor/vendor/phpunit|/vendor/vendor|/vendor/).*HTTP/.*"
            <HOST> -.*"(GET|POST).*(wp-login.php|xmlrpc.php|wp-admin).*HTTP/.*"
ignoreregex =
