# Detect attempts to access Docker API and /containers/json
[Definition]
failregex = <HOST> -.*"(GET|POST).*/containers/json.*HTTP/.*"
            <HOST> -.*"(GET|POST).*/v[0-9]+/containers.*HTTP/.*"
ignoreregex =
