# Detect LFI/RCE style payloads, lang=../../.., invokeFunction etc
[Definition]
failregex = <HOST> -.*"(GET|POST).*(\?\w*=.*\.\./\.\.|(\.\./){2,}|(invokeFunction|call_user_func_array|md5\(|phpinfo\(|system\(|exec\()).*HTTP/.*"
            <HOST> -.*"(GET|POST).*((think\\app|thinkphp|invokeFunction|call_user_func_array).*).*HTTP/.*"
ignoreregex =