name: Ansible CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ansible:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
      options: --user root

    steps:
      - name: Install system dependencies
        run: |
          dnf -y update
          dnf -y install epel-release
          dnf -y install python3 python3-pip git
          pip3 install --upgrade pip
          pip3 install ansible ansible-lint

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        run: ansible-lint site.yml --vault-password-file="${{ secrets.ANSIBLE_VAULT_PASSWORD }}"

      - name: Run ansible-playbook
        run: ansible-playbook -i inventory/test_hosts site.yml -e "env=test" --vault-password-file="${{ secrets.ANSIBLE_VAULT_PASSWORD }}"